name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Cancel in-progress runs when a new workflow with the same group name is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-ios:
    name: Test iOS
    runs-on: macos-26
    strategy:
      matrix:
        destination: 
          - "platform=iOS Simulator,name=iPhone 17,OS=26.0"
          - "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1"
          - "platform=iOS Simulator,name=iPhone 15,OS=17.5"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache DerivedData
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-derived-data-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-derived-data-
    
    - name: List Available Schemes
      run: xcodebuild -list
    
    - name: Build for Testing
      run: |
        xcodebuild build-for-testing \
          -scheme BackgroundTime \
          -destination "${{ matrix.destination }}" \
          -derivedDataPath DerivedData \
          -enableCodeCoverage YES \
          CODE_SIGNING_ALLOWED=NO \
          | xcpretty && exit ${PIPESTATUS[0]}
    
    - name: Run Tests
      run: |
        xcodebuild test-without-building \
          -scheme BackgroundTime \
          -destination "${{ matrix.destination }}" \
          -derivedDataPath DerivedData \
          -enableCodeCoverage YES \
          -resultBundlePath TestResults.xcresult \
          CODE_SIGNING_ALLOWED=NO \
          | xcpretty && exit ${PIPESTATUS[0]}
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-ios-${{ strategy.job-index }}
        path: TestResults.xcresult
    
    - name: Generate Code Coverage Report
      if: matrix.destination == 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1'
      run: |
        xcrun xccov view --report --json DerivedData/Logs/Test/*.xcresult > coverage.json
        xcrun xccov view --report DerivedData/Logs/Test/*.xcresult
    
    - name: Upload Coverage
      if: matrix.destination == 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-ios
        path: coverage.json

  test-macos:
    name: Test macOS
    runs-on: macos-26
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache DerivedData
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-derived-data-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-derived-data-
    
    - name: Build for Testing
      run: |
        xcodebuild build-for-testing \
          -scheme BackgroundTime \
          -destination "platform=macOS" \
          -derivedDataPath DerivedData \
          -enableCodeCoverage YES \
          CODE_SIGNING_ALLOWED=NO \
          | xcpretty && exit ${PIPESTATUS[0]}
    
    - name: Run Tests
      run: |
        xcodebuild test-without-building \
          -scheme BackgroundTime \
          -destination "platform=macOS" \
          -derivedDataPath DerivedData \
          -enableCodeCoverage YES \
          -resultBundlePath TestResults.xcresult \
          CODE_SIGNING_ALLOWED=NO \
          | xcpretty && exit ${PIPESTATUS[0]}
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-macos
        path: TestResults.xcresult
    
    - name: Generate Code Coverage Report
      run: |
        xcrun xccov view --report --json DerivedData/Logs/Test/*.xcresult > coverage.json
        xcrun xccov view --report DerivedData/Logs/Test/*.xcresult
    
    - name: Upload Coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-macos
        path: coverage.json

  documentation:
    name: Build Documentation
    runs-on: macos-26
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Documentation
      run: |
        xcodebuild docbuild \
          -scheme BackgroundTime \
          -destination "platform=macOS" \
          -derivedDataPath DerivedData
    
    - name: Process Documentation for Static Hosting
      run: |
        swift package --allow-writing-to-directory docs \
          generate-documentation --target BackgroundTime \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path BackgroundTime \
          --output-path docs
    
    - name: Upload Documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs

  lint:
    name: SwiftLint
    runs-on: macos-26
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint lint --strict