name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-ios:
    name: Test iOS
    runs-on: macos-latest
    strategy:
      matrix:
        destination: 
          - "platform=iOS Simulator,name=iPhone 15,OS=17.0"
          - "platform=iOS Simulator,name=iPhone 14,OS=16.0"
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Swift Package Resolve
      run: swift package resolve
    
    - name: Build
      run: swift build -v
    
    - name: Run Tests
      run: swift test -v

  test-macos:
    name: Test macOS
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Swift Package Resolve
      run: swift package resolve
    
    - name: Build for macOS
      run: swift build -v --arch arm64 --arch x86_64
    
    - name: Run Tests
      run: swift test -v

  documentation:
    name: Build Documentation
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer
    
    - name: Build Documentation
      run: |
        swift package --allow-writing-to-directory docs \
          generate-documentation --target BackgroundTime \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path BackgroundTime \
          --output-path docs

  lint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: SwiftLint
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict